#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "bitlab";
$SERVER_NAME = "turing.bowdoin.edu";
$SERVER_PORT = 8091;
$COURSE_NAME = "fcs";
$AUTOGRADE_TIMEOUT = 0;
1;
