int maxVal();
int test_maxVal();
int negCheck(int);
int test_negCheck(int);
int lsbCopy(int);
int test_lsbCopy(int);
int andBits(int, int);
int test_andBits(int, int);
int xorBits(int, int);
int test_xorBits(int, int);
int setThirdBits();
int test_setThirdBits();
int byteExtract(int, int);
int test_byteExtract(int, int);
int bitFit(int, int);
int test_bitFit(int, int);
int byteSwitch(int, int, int);
int test_byteSwitch(int, int, int);
int addOverflow(int, int);
int test_addOverflow(int, int);
int shiftLogical(int, int);
int test_shiftLogical(int, int);
int not(int);
int test_not(int);
int signMagnitude(int);
int test_signMagnitude(int);
unsigned fp_abs(unsigned);
unsigned test_fp_abs(unsigned);
unsigned fp_twice(unsigned);
unsigned test_fp_twice(unsigned);
